# Visual Synthesis Configuration

# Input paths
input:
  # Path to the 360-degree video dataset to use as canvas (null if not using video)
  # This should be a directory containing video files
  video_360_path: null
  # Path to the 360-degree image dataset to use as canvas
  # This should be a directory containing image files
  image_360_path: "/path/to/Img_360/"
  # Path to directory containing video assets by event class
  video_assets_dir: "/path/to/downloaded_video_assets/"
  # Path to directory containing image assets by event class
  image_assets_dir: "/path/to/flickr30k_images_per_class/"
  # Path to metadata directory containing metadata CSV files (DCASE metadata)
  metadata_dir: "/path/to/output_spatial_scaper/metadata"

# Output paths
output:
  # Directory to save generated videos
  video_dir: "/path/to/output/videos"
  log_file: "/path/to/output/processing_log.txt"

# Processing parameters
processing:
  # Number of worker processes to use (set to number of CPU cores you want to utilize)
  workers: 8
  # Video duration in seconds (if None, uses the duration from metadata)
  video_duration: 60
  # Video FPS
  fps: 30
  # Whether to use a dark background (True/False)
  dark_background: False
  # Whether to apply blur to the background (True/False)
  use_blur: False
  # Choose between image or video background
  use_image_background: True
